include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
      - java-mvn.yml
    ref: main

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "${IMAGE_REPOSITORY}"

stages:
  - docker-build


docker-build:
  variables:
    WORKING_DIR: "./myserver/"
    IMAGE_NAME: myserver
  stage: docker-build
  extends:
    - .kaniko:simple-build-push