apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myserver.fullname" . }}
  labels:
    {{- include "myserver.labels" . | nindent 4 }}
    app: myserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myserver.selectorLabels" . | nindent 6 }}
      app: myserver
  template:
    metadata:
      labels:
        {{- include "myserver.selectorLabels" . | nindent 8 }}
        app: myserver
    spec:
      # WHAT A BAD IDEA!!!!!! I know...
      serviceAccountName: bobsa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: token
                  key: token
          resources:
            {{- toYaml .Values.resources | nindent 12 }}